from enum import Enum
from typing import Dict, List

from pydantic import BaseModel, Field


# ============================================================================
# BUSINESS CONTEXT
# ============================================================================

class Industry(str, Enum):
    INSURANCE = "Insurance"
    BANKING = "Banking"
    HEALTHCARE = "Healthcare"
    RETAIL = "Retail"
    TELECOM = "Telecom"
    MANUFACTURING = "Manufacturing"
    ENERGY = "Energy"
    PUBLIC_SECTOR = "Public Sector"
    LIFE_SCIENCES = "Life Sciences"
    EDUCATION = "Education"
    TECHNOLOGY = "Technology"
    CROSS_INDUSTRY = "Cross Industry"
    OTHER = "Other"


class BusinessContext(BaseModel):
    """
    Business information extracted from the client scenario.
    """

    industry: Industry = Field(
        description="Industry associated with the use case."
    )

    use_case: str = Field(
        description="Business use case being evaluated."
    )


# ============================================================================
# WORKLOAD PROFILE
# ============================================================================

class WorkloadFamily(str, Enum):
    DOCUMENT_UNDERSTANDING = "Document Understanding"
    CONVERSATIONAL_AI = "Conversational AI"
    KNOWLEDGE_ASSISTANT = "Knowledge Assistant"
    SEARCH_AND_RAG = "Search and RAG"
    CONTENT_GENERATION = "Content Generation"
    CODE_GENERATION = "Code Generation"
    CLASSIFICATION = "Classification"
    DATA_ANALYSIS = "Data Analysis"
    AGENTIC_AUTOMATION = "Agentic Automation"
    MULTIMODAL = "Multimodal"
    TRANSLATION = "Translation"
    OTHER = "Other"


class TaskType(str, Enum):
    SUMMARIZATION = "Summarization"
    QUESTION_ANSWERING = "Question Answering"
    CHATBOT = "Chatbot"
    DOCUMENT_EXTRACTION = "Document Extraction"
    DOCUMENT_CLASSIFICATION = "Document Classification"
    REPORT_GENERATION = "Report Generation"
    KNOWLEDGE_SEARCH = "Knowledge Search"
    CONTENT_CREATION = "Content Creation"
    CODE_GENERATION = "Code Generation"
    CODE_REVIEW = "Code Review"
    TRANSLATION = "Translation"
    FRAUD_DETECTION = "Fraud Detection"
    IMAGE_ANALYSIS = "Image Analysis"
    IMAGE_GENERATION = "Image Generation"
    AGENT_WORKFLOW = "Agent Workflow"
    OTHER = "Other"


class Complexity(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    VERY_HIGH = "Very High"


class WorkloadProfile(BaseModel):
    """
    Workload classification generated by the Scenario Intelligence Agent.
    """

    workload_family: WorkloadFamily = Field(
        description="High-level workload family."
    )

    task_type: TaskType = Field(
        description="Specific workload task type."
    )

    complexity: Complexity = Field(
        description="Complexity of the workload."
    )

    context_window: str = Field(
        description="The maximum number of tokens (words/characters) the model can process in a single request"
    )


# ============================================================================
# REQUIRED CAPABILITIES
# ============================================================================

class Capability(str, Enum):
    REASONING = "Reasoning"
    LONG_CONTEXT = "Long Context"
    STRUCTURED_OUTPUT = "Structured Output"
    FUNCTION_CALLING = "Function Calling"
    TOOL_CALLING = "Tool Calling"
    RAG_SUPPORT = "RAG Support"
    PII_HANDLING = "PII Handling"
    MULTIMODAL = "Multimodal"
    OCR = "OCR"
    CODE_GENERATION = "Code Generation"
    LOW_LATENCY = "Low Latency"
    PRIVATE_DEPLOYMENT = "Private Deployment"
    FINE_TUNING = "Fine Tuning"
    AGENT_EXECUTION = "Agent Execution"


# ============================================================================
# BENCHMARK PLAN
# ============================================================================

class EvaluationMetric(str, Enum):
    ACCURACY = "Accuracy"
    FAITHFULNESS = "Faithfulness"
    HALLUCINATION = "Hallucination"
    LATENCY = "Latency"
    COST = "Cost"
    THROUGHPUT = "Throughput"
    REASONING_QUALITY = "Reasoning Quality"
    FACTUALITY = "Factuality"
    COMPLETENESS = "Completeness"
    RELEVANCE = "Relevance"
    ROBUSTNESS = "Robustness"
    SAFETY = "Safety"
    BIAS = "Bias"
    TOXICITY = "Toxicity"


class BenchmarkPlan(BaseModel):
    """
    Benchmark configuration generated by the Scenario Intelligence Agent.
    """

    evaluation_metrics: List[EvaluationMetric] = Field(
        default_factory=list,
        description="Metrics that should be used when evaluating candidate models."
    )

    weights: Dict[str, int] = Field(
        description=(
            "Relative importance of scoring dimensions. "
            "Typical keys are quality, governance, cost and latency. "
            "Values should add up to 100."
        ),
        example={
            "quality": 45,
            "governance": 25,
            "cost": 20,
            "latency": 10
        }
    )


# ============================================================================
# GOVERNANCE REQUIREMENTS
# ============================================================================

class Regulation(str, Enum):
    HIPAA = "HIPAA"
    GDPR = "GDPR"
    PCI_DSS = "PCI-DSS"
    SOC2 = "SOC2"
    ISO27001 = "ISO27001"
    CCPA = "CCPA"
    NIST = "NIST"
    FEDRAMP = "FedRAMP"


class Region(str, Enum):
    US = "US"
    EU = "EU"
    UK = "UK"
    CANADA = "Canada"
    INDIA = "India"
    AUSTRALIA = "Australia"
    JAPAN = "Japan"
    SINGAPORE = "Singapore"
    GLOBAL = "Global"


class GovernanceRequirements(BaseModel):
    """
    Compliance and data residency requirements.
    """

    regulations: List[Regulation] = Field(
        default_factory=list,
        description="Regulatory frameworks that candidate models must satisfy."
    )

    allowed_regions: List[Region] = Field(
        default_factory=list,
        description="Permitted deployment or data residency regions."
    )


# ============================================================================
# FINANCIAL CONSTRAINTS
# ============================================================================

class FinancialConstraints(BaseModel):
    """
    Financial constraints for model selection.
    """

    monthly_budget_usd: float = Field(
        ge=0,
        description="Maximum monthly budget in USD."
    )


# ============================================================================
# MASTER SCENARIO OUTPUT
# ============================================================================

class ScenarioEvaluationBlueprint(BaseModel):
    """
    Structured output produced by the
    Scenario Understanding + Workload Classification Agent.
    """

    business_context: BusinessContext

    workload_profile: WorkloadProfile

    required_capabilities: List[Capability] = Field(
        default_factory=list,
        description="Capabilities required from candidate models."
    )

    benchmark_plan: BenchmarkPlan

    governance_requirements: GovernanceRequirements

    financial_constraints: FinancialConstraints